apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo-app
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: k8s-frontend-demo-app
                port:
                  number: 80
          - pathType: Prefix
            path: "/api/v1/data:"
            backend:
              service:
                name: k8s-backend-demo-app
                port:
                  number: 8080