apiVersion: v1
kind: Service
metadata:
  name: pavelkostalcom-service
spec:
  selector:
    app: pavelkostalcom
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: LoadBalancer
