apiVersion: v1
kind: Service
metadata:
  name: photo-game-frontend-service
spec:
  selector:
    app: photo-game-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: LoadBalancer
