name: Backend Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'backend-demo-app/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./backend-demo-app/gradlew

      - name: Build with Gradle
        working-directory: ./backend-demo-app
        run: ./gradlew build

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend-demo-app
          push: true
          tags: pavelkostal/k8s-backend-demo-app:latest